package Problems;

import java.util.Iterator;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four 
 * million,find the sum of the even-valued terms.
 */


public class Problem2 {

	public static void main(String[] args) {
		int i=0,first=0,second=1,sum=0;
		while (i<4000000) {
		i=first+second;
		first=second;
		second=i;
		if(i%2==0) {
			sum=sum+i;
		}
		}
		System.out.println(sum);
	}
}